Repository nftstorage/nft.storage, pull requests merged in 2021-11, with the labels that each got.

#723 fix: survey button not opening modal
  packages/website/pages/files.js
Labels: P0

#745 In Progress: Feat/erc721 write-table
  .prettierignore
  Procfile
  packages/api/src/bindings.d.ts
  packages/api/src/utils/context.js
  packages/api/src/utils/router.js
  packages/database_v2/metadata/databases/default/tables/public_erc721_token_ingestion_queue.yaml
  packages/database_v2/metadata/databases/default/tables/tables.yaml
  packages/database_v2/migrations/default/1636399732590_ingestion_flat_table/down.sql
  packages/database_v2/migrations/default/1636399732590_ingestion_flat_table/up.sql
  packages/niftysave/gen/hasura/zeus/const.js
  packages/niftysave/gen/hasura/zeus/index.d.ts
  packages/niftysave/gen/hasura/zeus/index.js
  packages/niftysave/package.json
  packages/niftysave/scripts/generate-hasura.sh
  packages/niftysave/src/ingest-queue.js
  packages/niftysave/src/ingest/repo.js
Labels: niftysave

#775 fix (niftysave): subdivides 2021 into more processes
  Procfile
Labels: niftysave

#846 fix: status 5XX is not a valid status code
  packages/website/public/schema.yml
Labels: effort/quickwin
