Repository nftstorage/nft.storage, pull requests merged in 2022-06, with the labels that each got.

#1402 feat: DB schema and API for user_tag_proposal. (#1410)
  packages/api/db/migrations/003-user_tag_proposals.sql
  packages/api/db/tables.sql
Labels: status/in-progress

#2000 feat: followup #1945 after testing nft-ttr cron
  .github/workflows/cron-nft-ttr.yml
  .github/workflows/cron.yml
  packages/cron/package.json
  packages/cron/src/bin/nft-ttr.js
  packages/cron/src/bin/nft-ttr.spec.js
  packages/cron/src/jobs/measureNftTimeToRetrievability.js
  packages/cron/src/jobs/measureNftTimeToRetrievability.spec.js
  packages/cron/src/lib/metrics.js
  packages/cron/src/lib/time.js
  yarn.lock
Labels: kind/bug, pi/SLA

#2011 feat: Q3'22 integration blog post
  packages/website/posts/2022-06-22-spring-integration-spotlights.mdx
  packages/website/styles/markdown.css
Labels: pi/dotstorage-site-improvements
